### ISSUE TITLE
Invalid value at 'payload' (Map) ?

### ISSUE THREAD

**Issue by oriceon** [masbug/flysystem-google-drive-ext#104]
Hi. Any ideea about that?

```[2023-03-07 16:07:54] production.ERROR: {
  "error": {
    "code": 400,
    "message": "Invalid value at 'payload' (Map), Cannot bind a list to map for field 'exportLinks'.",
    "errors": [
      {
        "message": "Invalid value at 'payload' (Map), Cannot bind a list to map for field 'exportLinks'.",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "payload",
            "description": "Invalid value at 'payload' (Map), Cannot bind a list to map for field 'exportLinks'."
          }
        ]
      }
    ]
  }
}
 {"exception":"[object] (Google\\Service\\Exception(code: 400): {
  \"error\": {
    \"code\": 400,
    \"message\": \"Invalid value at 'payload' (Map), Cannot bind a list to map for field 'exportLinks'.\",
    \"errors\": [
      {
        \"message\": \"Invalid value at 'payload' (Map), Cannot bind a list to map for field 'exportLinks'.\",
        \"reason\": \"invalid\"
      }
    ],
    \"status\": \"INVALID_ARGUMENT\",
    \"details\": [
      {
        \"@type\": \"type.googleapis.com/google.rpc.BadRequest\",
        \"fieldViolations\": [
          {
            \"field\": \"payload\",
            \"description\": \"Invalid value at 'payload' (Map), Cannot bind a list to map for field 'exportLinks'.\"
          }
        ]
      }
    ]
  }
}
 at C:\\app\\vendor\\google\\apiclient\\src\\Http\\REST.php:134)
[stacktrace]
#0 C:\\app\\vendor\\google\\apiclient\\src\\Http\\REST.php(107): Google\\Http\\REST::decodeHttpResponse()
#1 [internal function]: Google\\Http\\REST::doExecute()
#2 C:\\app\\vendor\\google\\apiclient\\src\\Task\\Runner.php(187): call_user_func_array()
#3 C:\\app\\vendor\\google\\apiclient\\src\\Http\\REST.php(66): Google\\Task\\Runner->run()
#4 C:\\app\\vendor\\google\\apiclient\\src\\Client.php(916): Google\\Http\\REST::execute()
#5 C:\\app\\vendor\\google\\apiclient\\src\\Service\\Resource.php(238): Google\\Client->execute()
#6 C:\\app\\vendor\\google\\apiclient-services\\src\\Drive\\Resource\\Files.php(108): Google\\Service\\Resource->call()
#7 C:\\app\\vendor\\masbug\\flysystem-google-drive-ext\\src\\GoogleDriveAdapter.php(1378): Google\\Service\\Drive\\Resource\\Files->create()
#8 C:\\app\\vendor\\masbug\\flysystem-google-drive-ext\\src\\GoogleDriveAdapter.php(644): Masbug\\Flysystem\\GoogleDriveAdapter->createDir()
#9 C:\\app\\vendor\\league\\flysystem\\src\\Filesystem.php(95): Masbug\\Flysystem\\GoogleDriveAdapter->createDirectory()
#10 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\FilesystemAdapter.php(862): League\\Flysystem\\Filesystem->createDirectory()
#11 C:\\app\\app\\Services\\Utils\\Backup.php(152): Illuminate\\Filesystem\\FilesystemAdapter->makeDirectory()
#12 C:\\app\\app\\Listeners\\Backend\\Access\\BackupZipWasCreatedEventListener.php(19): App\\Services\\Utils\\Backup->encode()
#13 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(441): App\\Listeners\\Backend\\Access\\BackupZipWasCreatedEventListener->onZipWasCreated()
#14 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#15 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(435): Illuminate\\Events\\Dispatcher->dispatch()
#16 C:\\app\\vendor\\spatie\\laravel-backup\\src\\Tasks\\Backup\\BackupJob.php(311): event()
#17 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(740): Spatie\\Backup\\Tasks\\Backup\\BackupJob->Spatie\\Backup\\Tasks\\Backup\\{closure}()
#18 C:\\app\\vendor\\spatie\\laravel-backup\\src\\Tasks\\Backup\\BackupJob.php(310): rescue()
#19 C:\\app\\vendor\\spatie\\laravel-backup\\src\\Tasks\\Backup\\BackupJob.php(231): Spatie\\Backup\\Tasks\\Backup\\BackupJob->sendNotification()
#20 C:\\app\\vendor\\spatie\\laravel-backup\\src\\Tasks\\Backup\\BackupJob.php(166): Spatie\\Backup\\Tasks\\Backup\\BackupJob->createZipContainingEveryFileInManifest()
#21 C:\\app\\vendor\\spatie\\laravel-backup\\src\\Commands\\BackupCommand.php(58): Spatie\\Backup\\Tasks\\Backup\\BackupJob->run()
#22 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Spatie\\Backup\\Commands\\BackupCommand->handle()
#23 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(661): Illuminate\\Container\\BoundMethod::call()
#27 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(194): Illuminate\\Container\\Container->call()
#28 C:\\app\\vendor\\symfony\\console\\Command\\Command.php(312): Illuminate\\Console\\Command->execute()
#29 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(163): Symfony\\Component\\Console\\Command\\Command->run()
#30 C:\\app\\vendor\\spatie\\laravel-backup\\src\\Commands\\BaseCommand.php(28): Illuminate\\Console\\Command->run()
#31 C:\\app\\vendor\\symfony\\console\\Application.php(1022): Spatie\\Backup\\Commands\\BaseCommand->run()
#32 C:\\app\\vendor\\symfony\\console\\Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#33 C:\\app\\vendor\\symfony\\console\\Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#34 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(102): Symfony\\Component\\Console\\Application->run()
#35 C:\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(155): Illuminate\\Console\\Application->run()
#36 C:\\app\\artisan(34): Illuminate\\Foundation\\Console\\Kernel->handle()
#37 C:\\app\\artisan(3): sg_load()
#38 {main}
"} ```

**Comment by parallels999** [comment]
I did not find any `exportLinks` on sources, make a debug

**Comment by rudiboot** [comment]
I'm getting the same error when trying to create a folder. All the other functions are working, I can even create a file no problem.  I'm sure it was still working ok yesterday morning.

**Comment by parallels999** [comment]
Maybe google changes something, look at their repo for new issues

**Comment by parallels999** [comment]
https://github.com/googleapis/google-api-php-client-services/commit/4e0f81380cff43e0f986b6f714a4b82152f03c62 this commit was added yesterday, open an issue there

**Comment by rudiboot** [comment]
Any idea on how to fix this? It's happening for me when trying to create folders.

**Comment by masbug** [comment]
@rudiboot
Check your google-api-php-client-services version. If you're already using [v0.289.1](https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.289.1) then try to downgrade via composer.json. If not then try updating.

**Comment by rudiboot** [comment]
composer require google/apiclient-services:0.289.0
did the trick, thanks for your help @masbug
